---
development:
  cloud_name: dxqkokxv4
  api_key: '459489266943124'
  api_secret: 5pKVNSlqiTqbOtDxwdlxvpaxGIE
  enhance_image_tag: true
  static_image_support: false
  secure: true
production:
  cloud_name: dxqkokxv4
  api_key: '459489266943124'
  api_secret: 5pKVNSlqiTqbOtDxwdlxvpaxGIE
  enhance_image_tag: true
  static_image_support: true
  secure: true
test:
  cloud_name: dxqkokxv4
  api_key: '459489266943124'
  api_secret: 5pKVNSlqiTqbOtDxwdlxvpaxGIE
  enhance_image_tag: true
  static_image_support: false
  secure: true
