require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BannerPicturesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BannerPicture. As you add validations to BannerPicture, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BannerPicturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all banner_pictures as @banner_pictures" do
      banner_picture = BannerPicture.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:banner_pictures)).to eq([banner_picture])
    end
  end

  describe "GET #show" do
    it "assigns the requested banner_picture as @banner_picture" do
      banner_picture = BannerPicture.create! valid_attributes
      get :show, {:id => banner_picture.to_param}, valid_session
      expect(assigns(:banner_picture)).to eq(banner_picture)
    end
  end

  describe "GET #new" do
    it "assigns a new banner_picture as @banner_picture" do
      get :new, {}, valid_session
      expect(assigns(:banner_picture)).to be_a_new(BannerPicture)
    end
  end

  describe "GET #edit" do
    it "assigns the requested banner_picture as @banner_picture" do
      banner_picture = BannerPicture.create! valid_attributes
      get :edit, {:id => banner_picture.to_param}, valid_session
      expect(assigns(:banner_picture)).to eq(banner_picture)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BannerPicture" do
        expect {
          post :create, {:banner_picture => valid_attributes}, valid_session
        }.to change(BannerPicture, :count).by(1)
      end

      it "assigns a newly created banner_picture as @banner_picture" do
        post :create, {:banner_picture => valid_attributes}, valid_session
        expect(assigns(:banner_picture)).to be_a(BannerPicture)
        expect(assigns(:banner_picture)).to be_persisted
      end

      it "redirects to the created banner_picture" do
        post :create, {:banner_picture => valid_attributes}, valid_session
        expect(response).to redirect_to(BannerPicture.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved banner_picture as @banner_picture" do
        post :create, {:banner_picture => invalid_attributes}, valid_session
        expect(assigns(:banner_picture)).to be_a_new(BannerPicture)
      end

      it "re-renders the 'new' template" do
        post :create, {:banner_picture => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested banner_picture" do
        banner_picture = BannerPicture.create! valid_attributes
        put :update, {:id => banner_picture.to_param, :banner_picture => new_attributes}, valid_session
        banner_picture.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested banner_picture as @banner_picture" do
        banner_picture = BannerPicture.create! valid_attributes
        put :update, {:id => banner_picture.to_param, :banner_picture => valid_attributes}, valid_session
        expect(assigns(:banner_picture)).to eq(banner_picture)
      end

      it "redirects to the banner_picture" do
        banner_picture = BannerPicture.create! valid_attributes
        put :update, {:id => banner_picture.to_param, :banner_picture => valid_attributes}, valid_session
        expect(response).to redirect_to(banner_picture)
      end
    end

    context "with invalid params" do
      it "assigns the banner_picture as @banner_picture" do
        banner_picture = BannerPicture.create! valid_attributes
        put :update, {:id => banner_picture.to_param, :banner_picture => invalid_attributes}, valid_session
        expect(assigns(:banner_picture)).to eq(banner_picture)
      end

      it "re-renders the 'edit' template" do
        banner_picture = BannerPicture.create! valid_attributes
        put :update, {:id => banner_picture.to_param, :banner_picture => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested banner_picture" do
      banner_picture = BannerPicture.create! valid_attributes
      expect {
        delete :destroy, {:id => banner_picture.to_param}, valid_session
      }.to change(BannerPicture, :count).by(-1)
    end

    it "redirects to the banner_pictures list" do
      banner_picture = BannerPicture.create! valid_attributes
      delete :destroy, {:id => banner_picture.to_param}, valid_session
      expect(response).to redirect_to(banner_pictures_url)
    end
  end

end
